CREATE TABLE authors (
                         id SERIAL PRIMARY KEY,
                         author TEXT
);

CREATE TABLE books (
                       id SERIAL PRIMARY KEY,
                       book_name TEXT,
                       edition TEXT,
                       publication_year TEXT,
                       authors TEXT
);

INSERT INTO authors (author)
VALUES
    ('J.D. Salinger'),
    ('Herman Melville'),
    ('J.R.R. Tolkien'),
    ('Harper Lee'),
    ('George Orwell'),
    ('Jane Austen'),
    ('J.K. Rowling'),
    ('F. Scott Fitzgerald'),
    ('Leo Tolstoy'),
    ('Homer'),
    ('Lewis Carroll'),
    ('J.R.R. Tolkien'),
    ('Aldous Huxley'),
    ('Miguel de Cervantes'),
    ('C.S. Lewis'),
    ('Dante Alighieri'),
    ('Margaret Mitchell'),
    ('Mark Twain'),
    ('Charlotte Brontë'),
    ('Joseph Heller'),
    ('Mary Shelley'),
    ('Oscar Wilde'),
    ('Paulo Coelho'),
    ('William Golding'),
    ('Fyodor Dostoevsky'),
    ('John Steinbeck'),
    ('Emily Brontë'),
    ('Alexandre Dumas'),
    ('Fyodor Dostoevsky'),
    ('Gabriel García Márquez'),
    ('Leo Tolstoy'),
    ('Nathaniel Hawthorne'),
    ('Frances Hodgson Burnett'),
    ('Charles Dickens'),
    ('Charles Dickens'),
    ('Ernest Hemingway'),
    ('Victor Hugo'),
    ('Antoine de Saint-Exupéry');

INSERT INTO books (book_name, edition, publication_year, authors)
VALUES
    ('The Catcher in the Rye', 'First Edition', '1951', 'J.D. Salinger'),
    ('Moby-Dick', 'Original Edition', '1851', 'Herman Melville'),
    ('The Lord of the Rings', 'Anniversary Edition', '1954', 'J.R.R. Tolkien'),
    ('To Kill a Mockingbird', 'First Edition', '1960', 'Harper Lee'),
    ('1984', 'First Edition', '1949', 'George Orwell'),
    ('Pride and Prejudice', 'First Edition', '1813', 'Jane Austen'),
    ('Harry Potter and the Sorcerer''s Stone', 'First Edition', '1997', 'J.K. Rowling'),
    ('The Great Gatsby', 'First Edition', '1925', 'F. Scott Fitzgerald'),
    ('War and Peace', 'First Edition', '1869', 'Leo Tolstoy'),
    ('The Odyssey', 'First Edition', '8th century BC', 'Homer'),
    ('Alice''s Adventures in Wonderland', 'First Edition', '1865', 'Lewis Carroll'),
    ('The Hobbit', 'First Edition', '1937', 'J.R.R. Tolkien'),
    ('Brave New World', 'First Edition', '1932', 'Aldous Huxley'),
    ('Don Quixote', 'First Edition', '1605', 'Miguel de Cervantes'),
    ('The Chronicles of Narnia', 'First Edition', '1950', 'C.S. Lewis'),
    ('The Divine Comedy', 'First Edition', '1320', 'Dante Alighieri'),
    ('Gone with the Wind', 'First Edition', '1936', 'Margaret Mitchell'),
    ('The Adventures of Huckleberry Finn', 'First Edition', '1884', 'Mark Twain'),
    ('Jane Eyre', 'First Edition', '1847', 'Charlotte Brontë'),
    ('Catch-22', 'First Edition', '1961', 'Joseph Heller'),
    ('Frankenstein', 'First Edition', '1818', 'Mary Shelley'),
    ('The Picture of Dorian Gray', 'First Edition', '1890', 'Oscar Wilde'),
    ('The Alchemist', 'First Edition', '1988', 'Paulo Coelho'),
    ('Lord of the Flies', 'First Edition', '1954', 'William Golding'),
    ('Crime and Punishment', 'First Edition', '1866', 'Fyodor Dostoevsky'),
    ('The Grapes of Wrath', 'First Edition', '1939', 'John Steinbeck'),
    ('Wuthering Heights', 'First Edition', '1847', 'Emily Brontë'),
    ('The Count of Monte Cristo', 'First Edition', '1844', 'Alexandre Dumas'),
    ('The Brothers Karamazov', 'First Edition', '1880', 'Fyodor Dostoevsky'),
    ('One Hundred Years of Solitude', 'First Edition', '1967', 'Gabriel García Márquez'),
    ('Anna Karenina', 'First Edition', '1878', 'Leo Tolstoy'),
    ('The Scarlet Letter', 'First Edition', '1850', 'Nathaniel Hawthorne'),
    ('The Secret Garden', 'First Edition', '1911', 'Frances Hodgson Burnett'),
    ('Great Expectations', 'First Edition', '1861', 'Charles Dickens'),
    ('A Tale of Two Cities', 'First Edition', '1859', 'Charles Dickens'),
    ('The Old Man and the Sea', 'First Edition', '1952', 'Ernest Hemingway'),
    ('Les Misérables', 'First Edition', '1862', 'Victor Hugo'),
    ('The Little Prince', 'First Edition', '1943', 'Antoine de Saint-Exupéry'),
    ('The Catcher in the Rye', 'First Edition', '1951', 'J.D. Salinger'),
    ('Moby-Dick', 'Original Edition', '1851', 'Herman Melville'),
    ('The Lord of the Rings', 'Anniversary Edition', '1954', 'J.R.R. Tolkien'),
    ('To Kill a Mockingbird', 'First Edition', '1960', 'Harper Lee'),
    ('1984', 'First Edition', '1949', 'George Orwell'),
    ('Pride and Prejudice', 'First Edition', '1813', 'Jane Austen'),
    ('Harry Potter and the Sorcerer''s Stone', 'First Edition', '1997', 'J.K. Rowling'),
    ('The Great Gatsby', 'First Edition', '1925', 'F. Scott Fitzgerald'),
    ('War and Peace', 'First Edition', '1869', 'Leo Tolstoy'),
    ('The Odyssey', 'First Edition', '8th century BC', 'Homer'),
    ('Alice''s Adventures in Wonderland', 'First Edition', '1865', 'Lewis Carroll'),
    ('The Hobbit', 'First Edition', '1937', 'J.R.R. Tolkien'),
    ('Brave New World', 'First Edition', '1932', 'Aldous Huxley'),
    ('Don Quixote', 'First Edition', '1605', 'Miguel de Cervantes'),
    ('The Chronicles of Narnia', 'First Edition', '1950', 'C.S. Lewis'),
    ('The Divine Comedy', 'First Edition', '1320', 'Dante Alighieri'),
    ('Gone with the Wind', 'First Edition', '1936', 'Margaret Mitchell'),
    ('The Adventures of Huckleberry Finn', 'First Edition', '1884', 'Mark Twain'),
    ('Jane Eyre', 'First Edition', '1847', 'Charlotte Brontë'),
    ('Catch-22', 'First Edition', '1961', 'Joseph Heller'),
    ('Frankenstein', 'First Edition', '1818', 'Mary Shelley'),
    ('The Picture of Dorian Gray', 'First Edition', '1890', 'Oscar Wilde'),
    ('The Alchemist', 'First Edition', '1988', 'Paulo Coelho'),
    ('Lord of the Flies', 'First Edition', '1954', 'William Golding'),
    ('Crime and Punishment', 'First Edition', '1866', 'Fyodor Dostoevsky'),
    ('The Grapes of Wrath', 'First Edition', '1939', 'John Steinbeck'),
    ('Wuthering Heights', 'First Edition', '1847', 'Emily Brontë'),
    ('The Count of Monte Cristo', 'First Edition', '1844', 'Alexandre Dumas'),
    ('The Brothers Karamazov', 'First Edition', '1880', 'Fyodor Dostoevsky')
