version: '3'

services:
  postgres:
    image: postgres
    restart: always
    container_name: dialogbookstore
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: bookstore
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./bookstore.sql:/docker-entrypoint-initdb.d/bookstore.sql